apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql-namespace
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 329757168123.dkr.ecr.us-east-1.amazonaws.com/my-mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"