apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: web-namespace
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: 329757168123.dkr.ecr.us-east-1.amazonaws.com/my_app:latestV2.0
    ports:
    - containerPort: 80
    env:
    - name: DBHOST
      value: "10.244.0.45"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DATABASE
      value: "employees"
    - name: APP_COLOR
      value: "lime"