apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: web-namespace
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: 329757168123.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DBHOST
          value: "10.244.0.45"
        - name: DBPORT
          value: "3306" 
        - name: DBUSER
          value: "root" 
        - name: DBPWD 
          value: "pw"
        - name: DATABASE
          value: "employees" 
        - name: APP_COLOR
          value: "lime"